### ISSUE TITLE
Size responsive. 

### ISSUE THREAD

**Issue by vaneela** [vaneela/Random-color-Generator#4]
I don't want scrollbar in any screen size. Make it responsive.

**Comment by najeebkp** [comment]
Hi @vaneela Please assign this to me

**Comment by vaneela** [comment]
@najeebkp make PR I'll merge

**Comment by Arcturus22** [comment]
Is this Issue still open?
I would like to resolve this issue.

**Comment by vaneela** [comment]
yes it is open.

**Comment by vaneela** [comment]
but plz attach media of ur changes else I won't merge

**Comment by najeebkp** [comment]
@vaneela what about my PR?

**Comment by vaneela** [comment]
najeeb
attach media of ur changes plz i'll look
