### ISSUE TITLE
Changing color of Text!

### ISSUE THREAD

**Issue by shivanidotcom** [vaneela/Random-color-Generator#8]
I would like to change the color and font of the text "Random Color Generator".

**Comment by vaneela** [comment]
Sure make PR.

**Comment by shivanidotcom** [comment]
Updated Styling please look into it and accept my PR

**Comment by GAURAVKR007** [comment]
I have Done some work on this Repo [Random Color Generator]
 At Least check it out and Consider Mergeing
I have done a Pull Request Already
Thanks

**Comment by vaneela** [comment]
hey gaurav, I'll see after 20. So sorry for the late reply.
